### ISSUE TITLE
"Error generating autocomplete suggestions" on large project

### ISSUE THREAD

**Issue by macCesar** [appcelerator/titanium-vue#25]
Testing the extension with a large Alloy project throw this errors:

```
[2018-12-13 14:05:18.866] [renderer1] [info] standard startup
[2018-12-13 14:05:29.971] [renderer1] [warning] UNRESPONSIVE extension host, 'Zignd.html-css-class-completion' took 96% of 5400.073ms, saved PROFILE here: '/var/folders/2b/wq83cf7s7hx37v4l16jj407r0000gn/T/exthost-159d65.cpuprofile' [{"id":"gc","total":183408,"percentage":3},{"id":"program","total":23140,"percentage":0},{"id":"self","total":132,"percentage":0},{"id":"Zignd.html-css-class-completion","total":5187005,"percentage":96}]
[2018-12-13 14:05:36.996] [renderer1] [error] Failed to execute git
[2018-12-13 14:06:29.668] [renderer1] [error] Cannot read property 'regExp' of undefined: TypeError: Cannot read property 'regExp' of undefined
    at Object.provideDefinition (/Users/macCesar/.vscode/extensions/axway.vscode-titanium-0.1.1/out/providers/definition/definitionProviderHelper.js:121:24)
    at StyleDefinitionProvider.provideDefinition (/Users/macCesar/.vscode/extensions/axway.vscode-titanium-0.1.1/out/providers/definition/styleDefinitionProvider.js:35:41)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:553:442
    at t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:141:941)
    at new Promise (<anonymous>)
    at Object.t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:141:909)
    at e.provideDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:553:401)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:569:457
    at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:567:513)
    at e.$provideDefinition (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:569:419)
    at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
    at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)
    at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:60)
    at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
    at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)
    at Socket.n._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

```

**Comment by macCesar** [comment]
Sorry.. Wrong repo
